import type { Metadata } from "next";
import localFont from "next/font/local";
import '../styles/globals.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Filmes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}      >
         <header style={{
          backgroundColor: "green",
          textAlign: "center"
        }}>
  Catalogo de Filmes
</header>
        {children}
        <footer style={{
          marginTop: "200px", // Ajuste o valor conforme necessário
          marginBottom: "200px",
          textAlign: "center"
        }}>
  Bem vindo!
</footer>
      </body>
    </html>
  );
}
